[project]
name = "DRJ-Utils"
version = "0.1.0"
description = "Common utilities shared across my projects"
authors = [{ name = "Daniel Jackson", email = "daniel.r.jackson@gmail.com" }]
requires-python = "~=3.13"
readme = "README.md"
license = "CC BY-NC-ND 4.0"
dependencies = [
    "keyring>=25.6.0,<26",
    "pyyaml>=6.0.2,<7",
    "sympy>=1.13.3,<2",
]

[dependency-groups]
dev = [
    "coverage>=7.7.1,<8",
    "hypothesis>=6.130.4,<7",
    "pytest>=7.4.4,<8",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
    pythonpath = ["src"]
